# Generated by Django 5.0 on 2025-11-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('habilidad', models.CharField(max_length=50)),
                ('fuerza', models.IntegerField()),
                ('coste', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('ilustracion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion_intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cartas_banlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_banlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.banlist')),
                ('id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.carta')),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.edicion'),
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('nota_promedio', models.FloatField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cartas_mazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.carta')),
                ('id_mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.mazo')),
            ],
        ),
        migrations.CreateModel(
            name='Cartas_publicacion_intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.carta')),
                ('id_publicacion_intercambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.publicacion_intercambio')),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.tipo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=200)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('id_mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.mazo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('id_mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.mazo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.usuario'),
        ),
        migrations.CreateModel(
            name='Usuario_notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_promedio', models.FloatField()),
                ('id_mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.mazo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.usuario')),
            ],
        ),
    ]
