# Generated by Django 5.0 on 2025-12-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['nombre', 'id']},
        ),
    ]
