# Generated by Django 5.0 on 2025-12-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas_banlist',
            name='carta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.carta'),
        ),
        migrations.AlterField(
            model_name='cartas_banlist',
            name='edicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.edicion'),
        ),
        migrations.AlterField(
            model_name='cartas_banlist',
            name='restriccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.restriccion'),
        ),
    ]
