# Generated by Django 5.0 on 2025-11-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='edicion',
            new_name='id_edicion',
        ),
    ]
