# Generated by Django 5.0 on 2025-11-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion_intercambio',
            name='resumen',
        ),
    ]
