# Generated by Django 5.0 on 2025-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banlist',
            name='nombre',
            field=models.CharField(default='nombre-default', max_length=50),
        ),
    ]
