# Generated by Django 5.0 on 2025-11-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0002_banlist_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartas_banlist',
            name='id_banlist',
        ),
        migrations.RenameField(
            model_name='cartas_banlist',
            old_name='id_carta',
            new_name='carta',
        ),
        migrations.RemoveField(
            model_name='cartas_banlist',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cartas_banlist',
            name='edicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.edicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartas_banlist',
            name='restriccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.restriccion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Banlist',
        ),
    ]
