# Generated by Django 5.0 on 2025-11-21 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0002_publicacion_intercambio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
