# Generated by Django 5.0 on 2025-12-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0002_alter_carta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={},
        ),
    ]
