# Generated by Django 5.0 on 2025-11-29 22:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0003_mazo_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_usuario',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_mazo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='mazo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='plataformaYugimon.mazo'),
            preserve_default=False,
        ),
    ]
