# Generated by Django 5.0 on 2025-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0003_publicacion_intercambio_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion_intercambio',
            name='hora',
        ),
        migrations.AlterField(
            model_name='publicacion_intercambio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
