# Generated by Django 5.0 on 2025-12-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0003_alter_carta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_notas',
            name='id_mazo',
        ),
        migrations.RemoveField(
            model_name='usuario_notas',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Cartas_publicacion_intercambio',
        ),
        migrations.DeleteModel(
            name='Usuario_notas',
        ),
    ]
