# Generated by Django 5.0 on 2025-11-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0003_mazo_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_venta',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.categoriapost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion_venta',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
