# Generated by Django 5.0 on 2025-11-29 23:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0004_rename_id_usuario_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='plataformaYugimon.mazo'),
        ),
    ]
