# Generated by Django 5.0 on 2025-11-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0004_publicacion_venta_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_venta',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
