# Generated by Django 5.0 on 2025-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0004_remove_publicacion_intercambio_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='categoria',
            field=models.CharField(choices=[('CARTAS', 'Intercambio de Cartas'), ('MAZOS', 'Intercambio de Mazos')], default='CARTAS', max_length=255),
        ),
    ]
