# Generated by Django 5.0 on 2025-11-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0006_respuestacomentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestacomentario',
            options={'ordering': ['fecha']},
        ),
    ]
