# Generated by Django 5.0 on 2025-11-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0006_categoriaposts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaPosts',
            new_name='CategoriaPost',
        ),
    ]
