# Generated by Django 5.0 on 2025-11-30 21:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0007_alter_respuestacomentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestacomentario',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='mazo',
            name='nota_promedio',
        ),
        migrations.CreateModel(
            name='PuntuacionMazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.mazo')),
            ],
        ),
    ]
