# Generated by Django 5.0 on 2025-11-22 02:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0007_rename_categoriaposts_categoriapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_intercambio',
            name='categoria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publicacion_intercambio',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
