# Generated by Django 5.0 on 2025-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0008_alter_publicacion_intercambio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='resumen',
            field=models.CharField(default='Hace click para leer el articulo completo', max_length=255),
        ),
    ]
