# Generated by Django 5.0 on 2025-11-30 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0008_alter_respuestacomentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacionmazo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='puntuacionmazo',
            unique_together={('mazo', 'usuario')},
        ),
    ]
