# Generated by Django 5.0 on 2025-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0009_publicacion_intercambio_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='cartas_asociadas',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_intercambio', to='plataformaYugimon.carta'),
        ),
        migrations.AlterField(
            model_name='publicacion_intercambio',
            name='resumen',
            field=models.CharField(max_length=255),
        ),
    ]
