# Generated by Django 5.0 on 2025-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0010_publicacion_intercambio_cartas_asociadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion_intercambio',
            name='cartas_asociadas',
        ),
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='cartas_quiero',
            field=models.ManyToManyField(blank=True, related_name='cartas_quiero', to='plataformaYugimon.carta'),
        ),
        migrations.AddField(
            model_name='publicacion_intercambio',
            name='cartas_tengo',
            field=models.ManyToManyField(blank=True, related_name='cartas_tengo', to='plataformaYugimon.carta'),
        ),
    ]
