# Generated by Django 5.0 on 2025-11-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0011_remove_publicacion_intercambio_cartas_asociadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_intercambio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaYugimon.categoriapost'),
        ),
    ]
