# Generated by Django 5.0 on 2025-11-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaYugimon', '0012_alter_publicacion_intercambio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas_mazos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
